#
# 自分自身をアクションとして呼び出す
#
name: build

on: push

jobs:
  self_invocation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ルートFSオーバレイディレクトリの構成
      - name: configure rootfs overlay directory
        run: |
          mkdir rfs && cd rfs
          wget example.com

      # Raspberry Pi イメージのビルド
      - uses: Enchan1207/rpi-buildroot@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: buildroot.config
          pre_build_script: prebuild.sh
          post_build_script: postbuild.sh
          output_path: ./sdcard.img
          rootfs_overlay_dir: ./rfs

      # リリースドラフトを作成し、ビルドしたイメージを同梱
      - name: draft release
        uses: softprops/action-gh-release@v1
        with:
          name: release draft
          draft: true
          files: ./sdcard.img
