#
# 自分自身をアクションとして呼び出す
#
name: build

on: push

jobs:
  self_invocation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          ls -la /home/runner/work/_actions/Enchan1207/gha-sandbox

      - uses: Enchan1207/gha-sandbox@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: buildroot.config
