#
# 自分自身をアクションとして呼び出す
#
name: build

on: push

jobs:
  self_invocation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Raspberry Pi イメージのビルド
      - uses: Enchan1207/rpi-buildroot@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: buildroot.config
          pre_build_script: prebuild.sh
          post_build_script: postbuild.sh
          output_path: sdcard.img
          rootfs_overlay_dir: rfs
          buildroot_log_path: build.log

      # ビルドしたイメージとビルドログをアーティファクトとして保存
      - name: upload image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            sdcard.img
            build.log
